#!/usr/bin/env python3
"""Generate the SAM3D cache consumed by MOD training and inference."""

from __future__ import annotations

import argparse
from collections import Counter
import json
import math
import os
import shutil
from pathlib import Path
from typing import Any

from multi_object_decoder.cli import (
    scene_directory_name,
    validated_scene_directory_names,
)
from multi_object_decoder.data import load_manifest, load_scene
from multi_object_decoder.preparation import (
    SAM3DPrepareInference,
    generate_multi_object_cache,
)
from multi_object_decoder.sam3d_backend import SAM3DBackendError, load_sam3d_pipeline


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run the pinned SAM3D checkout once per manifest record and create "
            "tokens/obj_*.npz, img_cond_*.npy, local meshes and pose_inference.json."
        )
    )
    parser.add_argument("--data-json", type=Path, required=True)
    parser.add_argument("--sam3d-root", type=Path, default=os.environ.get("SAM3D_ROOT"))
    parser.add_argument(
        "--sam3d-config",
        type=Path,
        default=os.environ.get("SAM3D_PIPELINE_CONFIG"),
    )
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--background-value", type=int, default=0)
    parser.add_argument(
        "--absolute-paths",
        action="store_true",
        help="Write absolute paths instead of portable paths relative to prepared_data.json.",
    )
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument(
        "--generate-training-gt",
        action="store_true",
        help=(
            "Register fresh SAM3D meshes to each record's mesh_path using its "
            "explicit gt_object_map; write training targets in SAM3D prediction space."
        ),
    )
    parser.add_argument(
        "--gaps-binary",
        type=Path,
        default=os.environ.get("GAPS_MSHALIGN"),
        help="Path to GAPs mshalign, required with --generate-training-gt.",
    )
    parser.add_argument(
        "--gt-timeout", type=float, default=120.0,
        help="Timeout in seconds for each scene/object registration (default: 120).",
    )
    parser.add_argument(
        "--allow-legacy-pickle",
        action="store_true",
        help=(
            "Trust and reuse existing tokens/obj_*.npz caches that require pickle. "
            "New caches generated by this command are validated in-process without "
            "this flag."
        ),
    )
    parser.add_argument("--continue-on-error", action="store_true")
    return parser.parse_args()


def _resolved(path_value: Any, base: Path, field: str) -> Path:
    if path_value is None or not str(path_value).strip():
        raise ValueError(f"Manifest record is missing {field}")
    path = Path(str(path_value)).expanduser()
    return (base / path).resolve() if not path.is_absolute() else path.resolve()


def _serialized_path(path: Path, base: Path, absolute_paths: bool) -> str:
    resolved = path.expanduser().resolve()
    if absolute_paths:
        return str(resolved)
    return os.path.relpath(resolved, start=base)


def _record_identity(record: dict[str, Any]) -> str:
    """Return a stable view-level ID, not merely the possibly repeated scene ID."""

    scene_id = str(record["scene_id"])
    record_id = record.get("id")
    if isinstance(record_id, str) and record_id.strip():
        return record_id.strip()
    image_id = record.get("image_id")
    if image_id is not None and str(image_id).strip():
        return f"{scene_id}/{str(image_id).strip()}"
    if record_id is not None and str(record_id).strip():
        return f"{scene_id}/{str(record_id).strip()}"
    return scene_id


def _output_directory(record: dict[str, Any], base: Path, root: Path | None) -> Path:
    if root is not None:
        return root / scene_directory_name(_record_identity(record))
    if record.get("tokens_path"):
        return _resolved(record["tokens_path"], base, "tokens_path").parent
    if record.get("sam3d_canonical_dir"):
        canonical = _resolved(
            record["sam3d_canonical_dir"], base, "sam3d_canonical_dir"
        )
        return canonical.parent if canonical.name == "local_meshes" else canonical
    raise ValueError(
        "Each record needs tokens_path or sam3d_canonical_dir unless --output-dir is set"
    )


def _validated_output_root(
    requested: Path | None,
    manifest_dir: Path,
    *,
    overwrite: bool,
) -> Path | None:
    """Resolve an explicit output root and reject unsafe broad destinations."""

    if overwrite and requested is None:
        raise ValueError("--overwrite requires an explicit --output-dir")
    if requested is None:
        # Preserve the legacy, manifest-derived destination when no deletion was
        # requested. It remains intentionally unavailable to --overwrite.
        return None

    output_root = requested.expanduser().resolve()
    manifest_root = manifest_dir.expanduser().resolve()
    user_home = Path.home().expanduser().resolve()
    if output_root.parent == output_root:
        raise ValueError(f"Refusing filesystem root as --output-dir: {output_root}")
    if output_root == user_home:
        raise ValueError(f"Refusing the user home as --output-dir: {output_root}")
    if output_root == manifest_root:
        raise ValueError(
            f"Refusing the input manifest directory as --output-dir: {output_root}"
        )
    return output_root


def _validated_scene_output(
    output_dir: Path,
    output_root: Path,
    *,
    protected_paths: tuple[Path, ...] = (),
) -> Path:
    """Return a scene path only when it is a real strict child of the output root."""

    if output_dir.is_symlink():
        raise ValueError(f"Refusing symlink scene output directory: {output_dir}")
    resolved_output = output_dir.resolve()
    if resolved_output == output_root or output_root not in resolved_output.parents:
        raise ValueError(
            f"Scene output must be a strict child of --output-dir: {resolved_output}"
        )
    for protected in (Path.home(), *protected_paths):
        resolved_protected = protected.expanduser().resolve()
        if (
            resolved_output == resolved_protected
            or resolved_output in resolved_protected.parents
        ):
            raise ValueError(
                "Scene output must not contain a protected path such as the user "
                f"home or input manifest directory: {resolved_output}"
            )
    return resolved_output


def _remove_scene_output(
    output_dir: Path,
    output_root: Path,
    *,
    manifest_dir: Path | None = None,
) -> None:
    """Revalidate the exact scene path immediately before recursive deletion."""

    protected = () if manifest_dir is None else (manifest_dir,)
    safe_output = _validated_scene_output(
        output_dir,
        output_root,
        protected_paths=protected,
    )
    if safe_output.exists():
        shutil.rmtree(safe_output)


def _planned_output_directories(
    records: list[dict[str, Any]],
    manifest_dir: Path,
    output_root: Path | None,
) -> list[Path]:
    """Resolve every destination and reject collisions before pipeline startup."""

    identities = [_record_identity(record) for record in records]
    if output_root is not None:
        # Only explicit-root mode derives destinations from sanitized IDs. In
        # legacy mode the manifest paths below remain authoritative.
        validated_scene_directory_names(identities)
    outputs = []
    source_by_output: dict[Path, str] = {}
    for record, identity in zip(records, identities):
        output_dir = _output_directory(record, manifest_dir, output_root)
        if output_root is not None:
            output_dir = _validated_scene_output(
                output_dir,
                output_root,
                protected_paths=(manifest_dir,),
            )
        resolved_output = output_dir.resolve()
        if resolved_output in source_by_output:
            raise ValueError(
                "Manifest records map to the same scene output directory "
                f"{resolved_output}: {source_by_output[resolved_output]!r} and "
                f"{identity!r}"
            )
        source_by_output[resolved_output] = identity
        outputs.append(output_dir)
    return outputs


def _prepared_record(
    record: dict[str, Any],
    source_manifest_dir: Path,
    prepared_manifest_dir: Path,
    output_dir: Path,
    pose_path: Path,
    record_identity: str,
    absolute_paths: bool,
) -> dict[str, Any]:
    prepared = dict(record)
    original_scene_id = str(record["scene_id"])
    if record_identity != original_scene_id:
        prepared["source_scene_id"] = original_scene_id
        prepared["scene_id"] = record_identity
    for field in (
        "image_path",
        "instance_mask_path",
        "mesh_path",
        "scene_json_path",
        "gt_poses_path",
        "target_poses_path",
    ):
        value = prepared.get(field)
        if value is not None and str(value).strip():
            prepared[field] = _serialized_path(
                _resolved(value, source_manifest_dir, field),
                prepared_manifest_dir,
                absolute_paths,
            )
    prepared.update(
        {
            "tokens_path": _serialized_path(
                output_dir / "tokens", prepared_manifest_dir, absolute_paths
            ),
            "sam3d_canonical_dir": _serialized_path(
                output_dir / "local_meshes", prepared_manifest_dir, absolute_paths
            ),
            "base_poses_path": _serialized_path(
                pose_path, prepared_manifest_dir, absolute_paths
            ),
            "sam3d_pose_json": _serialized_path(
                pose_path, prepared_manifest_dir, absolute_paths
            ),
            "sam3d_mesh_path": _serialized_path(
                output_dir / "complete_multi_object_mesh.glb",
                prepared_manifest_dir,
                absolute_paths,
            ),
            "sam3d_results_path": _serialized_path(
                output_dir, prepared_manifest_dir, absolute_paths
            ),
            "time_path": _serialized_path(
                output_dir / "time.txt", prepared_manifest_dir, absolute_paths
            ),
        }
    )
    for stale_result_field in (
        "metrics_path",
        "midi_results_path",
        "ours_results_path",
        "partcrafter_results_path",
    ):
        prepared.pop(stale_result_field, None)
    prepared.pop("scene_npz_path", None)
    prepared.pop("scene_npz_paths", None)
    prepared.pop("cache_path", None)
    prepared.pop("sam3d_pose_path", None)
    return prepared


def _validate_prepared_output(
    prepared: dict[str, Any],
    prepared_manifest_dir: Path,
    output_dir: Path,
    expected_objects: Any,
    *,
    allow_legacy_pickle: bool,
    require_target: bool = False,
) -> None:
    """Reload the written cache through the authoritative training data loader."""

    sample = load_scene(
        prepared,
        prepared_manifest_dir,
        require_target=require_target,
        allow_legacy_pickle=allow_legacy_pickle,
    )
    if expected_objects is not None and sample.num_objects != int(expected_objects):
        raise RuntimeError(
            f"Expected {int(expected_objects)} objects but SAM3D produced "
            f"{sample.num_objects}"
        )
    missing_mesh_ids = []
    local_meshes = output_dir / "local_meshes"
    for object_id in sample.object_ids:
        candidates = (
            local_meshes / f"obj_{object_id}_local.ply",
            local_meshes / f"obj_{object_id:03d}_local.ply",
        )
        if not any(path.is_file() for path in candidates):
            missing_mesh_ids.append(object_id)
    if missing_mesh_ids:
        raise RuntimeError(f"Missing local SAM3D meshes for object IDs {missing_mesh_ids}")
    complete_mesh = output_dir / "complete_multi_object_mesh.glb"
    if not complete_mesh.is_file():
        raise RuntimeError(f"Missing combined SAM3D mesh: {complete_mesh}")


def _training_gt_input(
    record: dict[str, Any], manifest_dir: Path, output_dir: Path, *, overwrite: bool,
) -> tuple[Path, dict[str, str]]:
    """Require explicit GT geometry/correspondence before running SAM3D."""

    gt_scene = _resolved(record.get("mesh_path"), manifest_dir, "mesh_path")
    if not gt_scene.is_file():
        raise FileNotFoundError(f"Missing GT scene mesh: {gt_scene}")
    mapping = record.get("gt_object_map")
    if not isinstance(mapping, dict) or not mapping:
        raise ValueError(
            "--generate-training-gt requires a non-empty gt_object_map mapping "
            "SAM3D object IDs to GT scene node names (mask label minus one)."
        )
    if any(not isinstance(value, str) or not value.strip() for value in mapping.values()):
        raise ValueError("gt_object_map values must be non-empty GT scene node names")
    if overwrite and (output_dir.resolve() == gt_scene or output_dir.resolve() in gt_scene.parents):
        raise ValueError("Refusing to overwrite a scene output containing the source GT mesh")
    return gt_scene, mapping


def _attach_training_gt(
    prepared: dict[str, Any],
    *,
    gt_input: tuple[Path, dict[str, str]] | None,
    output_dir: Path,
    pose_path: Path,
    prepared_manifest_dir: Path,
    absolute_paths: bool,
    gaps_binary: Path | None,
    timeout: float,
) -> None:
    if gt_input is None:
        return
    from multi_object_decoder.training_gt import generate_training_gt

    target_path = output_dir / "target_poses.json"
    if gaps_binary is None:
        raise ValueError("--generate-training-gt requires --gaps-binary or GAPS_MSHALIGN")
    generate_training_gt(
        canonical_dir=output_dir / "local_meshes",
        base_poses_path=pose_path,
        gt_scene_path=gt_input[0],
        object_node_map=gt_input[1],
        output_path=target_path,
        gaps_binary=gaps_binary,
        timeout=timeout,
    )
    serialized = _serialized_path(target_path, prepared_manifest_dir, absolute_paths)
    prepared["target_poses_path"] = serialized
    prepared["gt_poses_path"] = serialized


def _load_external(sam3d_root: Path, config_path: Path):
    root = sam3d_root.expanduser().resolve()
    config = config_path.expanduser().resolve()
    # SAM3D's package initializer is not needed for pipeline construction and
    # may perform workstation-specific setup in older checkouts.
    os.environ.setdefault("LIDRA_SKIP_INIT", "true")
    try:
        pipeline = load_sam3d_pipeline(root, config, compile_model=False)
    except SAM3DBackendError as error:
        raise RuntimeError(
            "Could not load the SAM3D pipeline. Run scripts/prepare.sh with the "
            "official SAM3D environment (SAM3D_PYTHON) and verify its source and "
            f"checkpoint paths. Details: {error}"
        ) from error
    return SAM3DPrepareInference(pipeline), generate_multi_object_cache


def main() -> int:
    args = _parse_args()
    if args.generate_training_gt:
        if not math.isfinite(args.gt_timeout) or args.gt_timeout <= 0:
            raise ValueError("--gt-timeout must be a finite positive number")
        if args.gaps_binary is None:
            raise ValueError("--generate-training-gt requires --gaps-binary or GAPS_MSHALIGN")
        args.gaps_binary = args.gaps_binary.expanduser().resolve()
        if not args.gaps_binary.is_file() or not os.access(args.gaps_binary, os.X_OK):
            raise ValueError(f"GAPs mshalign is not an executable file: {args.gaps_binary}")
    manifest_path = args.data_json.expanduser().resolve()
    records = load_manifest(manifest_path)
    identities = [_record_identity(record) for record in records]
    identity_counts = Counter(identities)
    duplicate_identities = sorted(
        identity for identity, count in identity_counts.items() if count > 1
    )
    if duplicate_identities:
        preview = ", ".join(repr(value) for value in duplicate_identities[:5])
        raise ValueError(
            "Manifest records need unique id/image_id/scene_id identities; duplicates: "
            f"{preview}"
        )
    manifest_dir = manifest_path.parent
    output_root = _validated_output_root(
        args.output_dir,
        manifest_dir,
        overwrite=args.overwrite,
    )
    prepared_manifest_dir = output_root or manifest_dir
    prepared_manifest_path = prepared_manifest_dir / "prepared_data.json"
    if prepared_manifest_path.resolve() == manifest_path:
        raise ValueError(
            "The input manifest must not be the generated prepared_data.json; "
            "use a separate input manifest or --output-dir to preserve it on failure."
        )
    output_directories = _planned_output_directories(
        records,
        manifest_dir,
        output_root,
    )
    if args.overwrite:
        # One scene's output must not contain another scene's supervision or
        # raw inputs. Check the whole plan before deleting any cache directory.
        for record in records:
            for field in ("image_path", "instance_mask_path", "mesh_path",
                          "target_poses_path", "gt_poses_path"):
                value = record.get(field)
                if value is None or not str(value).strip():
                    continue
                source = _resolved(value, manifest_dir, field)
                for destination in output_directories:
                    resolved_destination = destination.resolve()
                    if source == resolved_destination or resolved_destination in source.parents:
                        raise ValueError(
                            f"Refusing --overwrite: scene output {destination} contains "
                            f"source {field} {source}; choose a new --output-dir."
                        )
    if args.sam3d_root is None or args.sam3d_config is None:
        raise ValueError(
            "--sam3d-root and --sam3d-config are required "
            "(or set SAM3D_ROOT and SAM3D_PIPELINE_CONFIG)"
        )
    # Reusing a trusted cache for GT registration does not need to load SAM3D weights.
    inference = generate = None
    summaries = []
    prepared_records = []
    had_error = False
    for record, output_dir in zip(records, output_directories):
        scene_id = _record_identity(record)
        try:
            image_path = _resolved(record.get("image_path"), manifest_dir, "image_path")
            mask_path = _resolved(
                record.get("instance_mask_path"), manifest_dir, "instance_mask_path"
            )
            if not image_path.is_file() or not mask_path.is_file():
                raise FileNotFoundError(
                    f"Missing image or instance mask: {image_path}, {mask_path}"
                )
            gt_input = (
                _training_gt_input(
                    record, manifest_dir, output_dir, overwrite=args.overwrite,
                )
                if args.generate_training_gt else None
            )
            if output_dir.exists() and args.overwrite:
                if output_root is None:  # Defensive; rejected before pipeline loading.
                    raise RuntimeError("--overwrite requires a validated --output-dir")
                _remove_scene_output(
                    output_dir,
                    output_root,
                    manifest_dir=manifest_dir,
                )
            existing_tokens = sorted((output_dir / "tokens").glob("obj_*.npz"))
            pose_path = output_dir / "pose_inference.json"
            if existing_tokens and pose_path.is_file() and not args.overwrite:
                if not args.allow_legacy_pickle:
                    raise RuntimeError(
                        "Refusing to reuse an existing legacy obj_*.npz cache because "
                        "it requires pickle; verify that the cache is trusted, then "
                        "rerun with --allow-legacy-pickle"
                    )
                prepared = _prepared_record(
                    record,
                    manifest_dir,
                    prepared_manifest_dir,
                    output_dir,
                    pose_path,
                    scene_id,
                    args.absolute_paths,
                )
                _attach_training_gt(
                    prepared, gt_input=gt_input, output_dir=output_dir, pose_path=pose_path,
                    prepared_manifest_dir=prepared_manifest_dir,
                    absolute_paths=args.absolute_paths, gaps_binary=args.gaps_binary,
                    timeout=args.gt_timeout,
                )
                _validate_prepared_output(
                    prepared,
                    prepared_manifest_dir,
                    output_dir,
                    record.get("num_parts", record.get("num_objects")),
                    allow_legacy_pickle=True,
                    require_target=args.generate_training_gt,
                )
                summaries.append(
                    {
                        "scene_id": scene_id,
                        "status": "success" if args.generate_training_gt else "skipped",
                        "cache_status": "reused",
                        "training_gt_generated": args.generate_training_gt,
                        "output_dir": _serialized_path(
                            output_dir,
                            prepared_manifest_dir,
                            args.absolute_paths,
                        ),
                    }
                )
                prepared_records.append(prepared)
                continue
            if output_dir.exists() and any(output_dir.iterdir()) and not args.overwrite:
                raise RuntimeError(
                    f"Incomplete existing output at {output_dir}; rerun with --overwrite"
                )
            output_dir.mkdir(parents=True, exist_ok=True)
            if generate is None:
                inference, generate = _load_external(args.sam3d_root, args.sam3d_config)
            result = generate(
                inference=inference,
                image_path=image_path,
                mask_path=mask_path,
                output_dir=output_dir,
                seed=args.seed,
                background_value=args.background_value,
                save_image_condition_only=False,
                save_tokens_only=False,
            )
            if result.get("status") != "success" or int(result.get("num_objects", 0)) <= 0:
                raise RuntimeError(result.get("error", "SAM3D produced no objects"))
            poses = result.get("poses")
            if not isinstance(poses, dict) or not poses:
                raise RuntimeError("SAM3D did not return baseline object poses")
            pose_path.write_text(
                json.dumps({"objects": poses}, indent=2) + "\n", encoding="utf-8"
            )
            token_files = sorted((output_dir / "tokens").glob("obj_*.npz"))
            condition_files = sorted((output_dir / "tokens").glob("img_cond_*.npy"))
            if len(token_files) != len(poses) or len(condition_files) != len(poses):
                raise RuntimeError(
                    "Incomplete SAM3D cache: "
                    f"poses={len(poses)}, tokens={len(token_files)}, "
                    f"image_conditions={len(condition_files)}"
                )
            prepared = _prepared_record(
                record,
                manifest_dir,
                prepared_manifest_dir,
                output_dir,
                pose_path,
                scene_id,
                args.absolute_paths,
            )
            _attach_training_gt(
                prepared, gt_input=gt_input, output_dir=output_dir, pose_path=pose_path,
                prepared_manifest_dir=prepared_manifest_dir,
                absolute_paths=args.absolute_paths, gaps_binary=args.gaps_binary,
                timeout=args.gt_timeout,
            )
            _validate_prepared_output(
                prepared,
                prepared_manifest_dir,
                output_dir,
                record.get("num_parts", record.get("num_objects")),
                # These files were produced by the pipeline in this process, so
                # their object arrays have not crossed a trust boundary.
                allow_legacy_pickle=True,
                require_target=args.generate_training_gt,
            )
            prepared_records.append(prepared)
            summaries.append(
                {
                    "scene_id": scene_id,
                    "status": "success",
                    "training_gt_generated": args.generate_training_gt,
                    "objects": len(poses),
                    "output_dir": _serialized_path(
                        output_dir,
                        prepared_manifest_dir,
                        args.absolute_paths,
                    ),
                }
            )
        except Exception as error:
            had_error = True
            summaries.append(
                {
                    "scene_id": scene_id,
                    "status": "failed",
                    "error": f"{type(error).__name__}: {error}",
                }
            )
            if not args.continue_on_error:
                break
    prepared_manifest_path.parent.mkdir(parents=True, exist_ok=True)
    prepared_manifest_path.write_text(
        json.dumps(prepared_records, indent=2) + "\n", encoding="utf-8"
    )
    report = {
        "prepared_manifest": _serialized_path(
            prepared_manifest_path,
            prepared_manifest_dir,
            args.absolute_paths,
        ),
        "scenes": summaries,
        "successful": sum(row["status"] == "success" for row in summaries),
        "failed": sum(row["status"] == "failed" for row in summaries),
        "skipped": sum(row["status"] == "skipped" for row in summaries),
    }
    destination = prepared_manifest_dir / "prepare_manifest.json"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2))
    return 1 if had_error else 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        raise SystemExit(130)
